<a href="https://colab.research.google.com/github/revaanwarr/pemrograman-lanjut/blob/main/Lab%20Matriks%20-%20Reva%20Anwar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**🖥️👩🏻‍💻PRAKTIKUM PEMROGRAMAN LANJUT🔥**
##**MATRIKS PYTHON - Senin, 09 Desember 2024**

👤 Nama: Reva Anwar / NRP: 2C2230003 / Kelas: III/A Sains Data






#🤸🏻‍♀️ EKSPLORASI PRIBADI DI KELAS ✨

Matriks pada dasarnya adalah array 2 dimensi. Matriks dapat dideklarasikan dengan:

In [ ]:
A = [[0 for j in range (20)] for i in range (10)]

Pada kode di atas, artinya kita membuat matriks dengan nama variabel A, dengan tipe elemen integer dan nilai awal 0, dan berukuran 10 baris 20 kolom. Sama seperti array, untuk mengakses elemen baris le-i dan kolom ke-j, kita perlu mengakses Ali-1][j-1] karena indeks matriks dimulai dari 0

Sehagai contoh, berikut kode untuk membaca matriks dan menuliskannya kembali:

In [ ]:
n = int(input())
m = int(input())

A = [[0 for j in range(m)] for i in range(n)]

1
2


In [ ]:
import numpy as np
x1 = np.array([[2,3,4],
 [2,5,6],
 [6,7,8]])
x1

array([[2, 3, 4],
       [2, 5, 6],
       [6, 7, 8]])

In [ ]:
import numpy as np
x1 = np.array([[2,3,4], [2,5,6], [6,7,8]])
x1

array([[2, 3, 4],
       [2, 5, 6],
       [6, 7, 8]])

In [ ]:
ls = [[2,3,4],
   [2,5,6],
   [6,7,8]]
ls

[[2, 3, 4], [2, 5, 6], [6, 7, 8]]

In [ ]:
A = [[0 for j in range(20)] for i in range(10)]
A

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [ ]:
x2 = np.dot(x1,x1)
x2

array([[ 34,  49,  58],
       [ 50,  73,  86],
       [ 74, 109, 130]])

#🧠 LATIHAN SOAL DI KELAS ⏱️

**Matriks Segitiga Paskal**

In [ ]:
n = 5  # Ubah nilai n untuk mengubah ukuran segitiga Pascal

pascal = [[1]]
for i in range(1, n):
    baris_baru = [1]
    for j in range(1, i):
        baris_baru.append(pascal[i-1][j-1] + pascal[i-1][j])
    baris_baru.append(1)
    pascal.append(baris_baru)

for baris in pascal:
    print(baris)

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]


**LINEAR ALGEBRA**


1.1 Determinan Matriks

In [ ]:
import numpy as np

# Definisi matriks A dan B
A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 3, 0], [2, 1, -5], [1, 4, -2]])

# Hitung determinan
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

# Tampilkan hasil
print("Determinan matriks A:", det_A)
print("Determinan matriks B:", det_B)

Determinan matriks A: -2.0000000000000004
Determinan matriks B: -21.00000000000001


In [ ]:
import numpy as np

# Tentukan Determinan
# Matriks A
A = np.array([[1, 2],
              [3, 4]])

# Matriks B
B = np.array([[-1, 3, 0],
              [2, 1, -5],
              [1, 4, -2]])

# Menghitung determinan
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

print("Determinan matriks A:", round(det_A))
print("Determinan matriks B:", round(det_B))

Determinan matriks A: -2
Determinan matriks B: -21


1.2 Transpose Matriks

In [ ]:
# Matriks A untuk transpose
A_transpose = np.array([[1, 3, 7, 2],
                        [5, 8, -9, 0],
                        [6, -7, 11, 12]])

# Menghitung transpose
transpose_A = A_transpose.T

print("Transpose matriks A:")
print(transpose_A)

Transpose matriks A:
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]


#🏆 POST TEST 🎯

- Interpretasi coding:
- Interpretasi hasil:

📌Catatan:
  - Notebook python ini dibuat untuk memudahkan temen-temen belajar ngoding dan pengumpulan tugas.
  - Silakan download notebook ini lalu upload di Google Collab milik kalian agar format `pertemuan`, `topik pertemuan`,
`tanggal`, `deskripsi pembahasan materi`, `baris coding` dan `interpretasi` bisa disesuaikan dengan kebutuhan teman-teman.

  - Interpretasi coding dan hasil dimaksudkan agar teman-teman semakin memahami apa yang dipelajari.

  - Deskripsi pembahasan materi dimaksudkan agar teman-teman semakin memahami apa fokus yang dipelajari.

  - Tulisan di setiap sebelum baris code disebut `markdown`. Ada beberapa jenis simbol yang memudahkan kepenulisan `markdown` kita, yaitu seperti : untuk mengatur ukuran tulisan biasanya tulisan pada header menggunakan ini`#`, `##`, `###`, untuk membuat pointer menggunakan ini `-`, untuk membuat tulisan ter-highlight menggunakan ini *` `* , untuk short-cut membuat tulisan jadi **bold** gunakan ini `** **`, dan untuk *tulisan miring* gunakan ini `* *` .

  - Semangat belajar! 🌟✨

©️ LABORATORIUM SAINS DATA 2024